"""Hypernetwork and connection visualization for CubeMind.

Renders real-time views of:
  - HYLA hypernetwork weight magnitudes (which connections are active)
  - Block-code activation patterns (which blocks fire)
  - MoE expert routing graph (which experts are selected)
  - HMM state transition heatmap (which rules are active)

Supports both static paper-quality plots and live updating views.

Usage:
    from cubemind.telemetry.network_viz import NetworkVisualizer

    viz = NetworkVisualizer()

    # Snapshot after one forward pass
    viz.plot_hyla_weights(W, save="figures/hyla_weights.pdf")
    viz.plot_block_activations(block_code, save="figures/blocks.pdf")
    viz.plot_expert_routing(gate_weights, topic_names, save="figures/routing.pdf")
    viz.plot_hmm_transitions(A, state_names, save="figures/hmm.pdf")

    # Live mode — updates in real-time during inference
    viz.live_hyla(hyla_module)  # opens a window that updates each forward pass
"""

from __future__ import annotations

from pathlib import Path

import numpy as np


class NetworkVisualizer:
    """Visualization toolkit for CubeMind's neural-symbolic network.

    All methods work with raw numpy arrays — no dependency on the
    modules themselves, only their weight/activation data.
    """

    def __init__(self, font_size: int = 11) -> None:
        self._font_size = font_size

    def _setup(self):
        import matplotlib.pyplot as plt
        import matplotlib
        matplotlib.rcParams.update({
            "font.size": self._font_size,
            "figure.dpi": 150,
            "savefig.dpi": 300,
            "savefig.bbox": "tight",
        })
        return plt

    def _save_or_show(self, fig, save):
        if save:
            path = Path(save)
            path.parent.mkdir(parents=True, exist_ok=True)
            fig.savefig(str(path))
        else:
            import matplotlib.pyplot as plt
            plt.show()

    # ── HYLA Hypernetwork Weights ─────────────────────────────────────

    def plot_hyla_weights(
        self,
        W: np.ndarray,
        title: str = "HYLA Generated Weights",
        threshold: float = 0.01,
        save: str | None = None,
    ) -> dict:
        """Visualize hypernetwork-generated weight matrix.

        Shows which connections are active (above threshold) vs inactive.
        Returns statistics about network sparsity.

        Args:
            W: Weight matrix of shape (d_out, d_in) generated by HYLA.
            title: Plot title.
            threshold: Absolute value below which a connection is "inactive".
            save: Path to save figure.

        Returns:
            dict with: sparsity, active_ratio, mean_magnitude, max_magnitude
        """
        plt = self._setup()

        abs_W = np.abs(W)
        active_mask = abs_W > threshold
        active_ratio = float(active_mask.sum()) / active_mask.size
        sparsity = 1.0 - active_ratio

        fig, axes = plt.subplots(1, 3, figsize=(16, 5))

        # 1. Full weight heatmap
        im1 = axes[0].imshow(W, aspect="auto", cmap="RdBu_r",
                              vmin=-np.abs(W).max(), vmax=np.abs(W).max())
        axes[0].set_title("Weight Matrix")
        axes[0].set_xlabel("Input dim")
        axes[0].set_ylabel("Output dim")
        plt.colorbar(im1, ax=axes[0], shrink=0.8)

        # 2. Active/inactive binary map
        axes[1].imshow(active_mask.astype(float), aspect="auto", cmap="Greens",
                        vmin=0, vmax=1)
        axes[1].set_title(f"Active Connections ({active_ratio:.1%})")
        axes[1].set_xlabel("Input dim")
        axes[1].set_ylabel("Output dim")

        # 3. Weight magnitude distribution
        flat = abs_W.ravel()
        axes[2].hist(flat, bins=100, color="#0072B2", alpha=0.7, edgecolor="white")
        axes[2].axvline(threshold, color="#D55E00", linestyle="--",
                         label=f"Threshold={threshold}")
        axes[2].set_xlabel("Absolute Weight")
        axes[2].set_ylabel("Count")
        axes[2].set_title("Weight Distribution")
        axes[2].legend()
        axes[2].set_yscale("log")

        fig.suptitle(f"{title}  —  Sparsity: {sparsity:.1%}", fontsize=self._font_size + 3)
        fig.tight_layout()
        self._save_or_show(fig, save)

        return {
            "sparsity": sparsity,
            "active_ratio": active_ratio,
            "mean_magnitude": float(abs_W.mean()),
            "max_magnitude": float(abs_W.max()),
        }

    # ── Block-Code Activations ────────────────────────────────────────

    def plot_block_activations(
        self,
        block_code: np.ndarray,
        title: str = "Block-Code Activation",
        save: str | None = None,
    ) -> None:
        """Visualize a block-code vector as a heatmap.

        Each row is a block, columns are positions within the block.
        One-hot patterns show as single bright pixels per row.

        Args:
            block_code: Block-code vector of shape (k, l).
            title: Plot title.
            save: Path to save figure.
        """
        plt = self._setup()
        fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 5),
                                         gridspec_kw={"width_ratios": [3, 1]})

        # Heatmap
        im = ax1.imshow(block_code, aspect="auto", cmap="viridis")
        ax1.set_xlabel("Position within block")
        ax1.set_ylabel("Block index")
        ax1.set_title(title)
        plt.colorbar(im, ax=ax1, shrink=0.8)

        # Per-block max activation
        max_vals = block_code.max(axis=1)
        block_code.argmax(axis=1)
        ax2.barh(range(len(max_vals)), max_vals, color="#009E73", alpha=0.8)
        ax2.set_xlabel("Max activation")
        ax2.set_ylabel("Block")
        ax2.set_title("Peak per block")
        ax2.invert_yaxis()

        fig.tight_layout()
        self._save_or_show(fig, save)

    # ── Expert Routing Graph ──────────────────────────────────────────

    def plot_expert_routing(
        self,
        gate_weights: np.ndarray,
        expert_names: list[str] | None = None,
        title: str = "MoE Expert Routing",
        save: str | None = None,
    ) -> None:
        """Visualize mixture-of-experts gate weights as a bar chart.

        Args:
            gate_weights: 1D array of expert weights (num_experts,).
            expert_names: Optional list of expert/topic names.
            title: Plot title.
            save: Path to save figure.
        """
        plt = self._setup()
        n = len(gate_weights)
        if expert_names is None:
            expert_names = [f"Expert {i}" for i in range(n)]

        fig, ax = plt.subplots(figsize=(max(8, n * 0.8), 5))

        colors = ["#D55E00" if w > 0.1 else "#56B4E9" for w in gate_weights]
        bars = ax.bar(range(n), gate_weights, color=colors, alpha=0.85, edgecolor="white")
        ax.set_xticks(range(n))
        ax.set_xticklabels(expert_names, rotation=45, ha="right")
        ax.set_ylabel("Gate Weight")
        ax.set_title(title)

        # Annotate active experts
        for i, (bar, w) in enumerate(zip(bars, gate_weights)):
            if w > 0.01:
                ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 0.005,
                        f"{w:.3f}", ha="center", va="bottom", fontsize=self._font_size - 2)

        fig.tight_layout()
        self._save_or_show(fig, save)

    # ── HMM Transition Heatmap ────────────────────────────────────────

    def plot_hmm_transitions(
        self,
        A: np.ndarray,
        state_names: list[str] | None = None,
        title: str = "HMM Transition Matrix",
        save: str | None = None,
    ) -> None:
        """Visualize HMM transition matrix as a heatmap.

        Args:
            A: Transition matrix of shape (n_states, n_states).
            state_names: Optional state labels.
            title: Plot title.
            save: Path to save figure.
        """
        plt = self._setup()
        n = A.shape[0]
        if state_names is None:
            state_names = [f"S{i}" for i in range(n)]

        fig, ax = plt.subplots(figsize=(max(6, n * 0.5), max(5, n * 0.4)))

        im = ax.imshow(A, cmap="YlOrRd", vmin=0, vmax=A.max())
        ax.set_xticks(range(n))
        ax.set_yticks(range(n))
        ax.set_xticklabels(state_names, rotation=45, ha="right")
        ax.set_yticklabels(state_names)
        ax.set_xlabel("To state")
        ax.set_ylabel("From state")
        ax.set_title(title)
        plt.colorbar(im, ax=ax, shrink=0.8)

        # Annotate cells
        for i in range(n):
            for j in range(n):
                val = A[i, j]
                if val > 0.01:
                    color = "white" if val > A.max() * 0.6 else "black"
                    ax.text(j, i, f"{val:.2f}", ha="center", va="center",
                            color=color, fontsize=max(6, self._font_size - 3))

        fig.tight_layout()
        self._save_or_show(fig, save)

    # ── Full Pipeline Snapshot ────────────────────────────────────────

    def plot_pipeline_snapshot(
        self,
        block_code: np.ndarray | None = None,
        gate_weights: np.ndarray | None = None,
        hyla_weights: np.ndarray | None = None,
        hmm_A: np.ndarray | None = None,
        expert_names: list[str] | None = None,
        save: str | None = None,
    ) -> None:
        """Full pipeline visualization in a single figure.

        Shows block-code, routing, HYLA weights, and HMM transitions
        side by side for a complete snapshot of one inference step.
        """
        plt = self._setup()

        panels = sum(x is not None for x in [block_code, gate_weights, hyla_weights, hmm_A])
        if panels == 0:
            return

        fig, axes = plt.subplots(1, panels, figsize=(5 * panels, 5))
        if panels == 1:
            axes = [axes]

        idx = 0
        if block_code is not None:
            axes[idx].imshow(block_code, aspect="auto", cmap="viridis")
            axes[idx].set_title("Block-Code")
            idx += 1

        if gate_weights is not None:
            n = len(gate_weights)
            colors = ["#D55E00" if w > 0.1 else "#56B4E9" for w in gate_weights]
            axes[idx].bar(range(n), gate_weights, color=colors)
            axes[idx].set_title("Expert Routing")
            idx += 1

        if hyla_weights is not None:
            abs_W = np.abs(hyla_weights)
            axes[idx].imshow(abs_W, aspect="auto", cmap="hot")
            sparsity = (abs_W < 0.01).sum() / abs_W.size
            axes[idx].set_title(f"HYLA Weights ({sparsity:.0%} sparse)")
            idx += 1

        if hmm_A is not None:
            axes[idx].imshow(hmm_A, cmap="YlOrRd")
            axes[idx].set_title("HMM Transitions")
            idx += 1

        fig.suptitle("CubeMind Pipeline Snapshot", fontsize=self._font_size + 3)
        fig.tight_layout()
        self._save_or_show(fig, save)
